### PR TITLE
Update ember and add demon hunter

### PR DESCRIPTION
**Pull request by ianlamb**
Umm, all I wanted to do was add demon hunter but since NPM 3 broke something in the old version of Ember I just went ahead and upgraded it and migrated all the stuff that broke :)

Btw I think your staging instance of byfirebepurged is broken, I just get 404s when running this locally against it.

### CODE REVIEW

**Comment by kelsin** [comment]
I'll look at fixes tests after mythics tonight. You have to show me how you learned to do this so fast... I was going to hunker down and do it later....

**Comment by byronh** [comment]
Ian's a wizard.

**Comment by ianlamb** [comment]
I'm a wot

**Comment by kelsin** [comment]
What steps did you do to update Ian? Looks like some things are broken, and trying to figure out what. My assumption is that ember-data has a lot of changes that we need to account for.

**Comment by ianlamb** [comment]
I pretty much just did `ember init` and diffed the changes. Then for everything that was broken or had a deprecation warning I looked it up and there were usually migration guides or something on it.

**Comment by kelsin** [comment]
Looks like the use of `Ember.View` is getting by some deprecation warnings but still triggering problems on the site, going to attempt to update to 1.13 first (last version prior to 2.0) and fix all warnings one by one, then do a update to 2.0.

**Pull request closed without merging**
